// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjsbKMDPdDJObUtNQabsrsG6IbCX2pSQ4',
    appId: '1:706091428534:web:161c2da567190867c89417',
    messagingSenderId: '706091428534',
    projectId: 'claudiawongproject',
    authDomain: 'claudiawongproject.firebaseapp.com',
    storageBucket: 'claudiawongproject.firebasestorage.app',
    measurementId: 'G-3GHP71HX0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQCe2yW3gaj5VkWD2YezgRiwNpNs9PqwY',
    appId: '1:706091428534:android:196760e17bf3a272c89417',
    messagingSenderId: '706091428534',
    projectId: 'claudiawongproject',
    storageBucket: 'claudiawongproject.firebasestorage.app',
  );
}
